# Generated by Django 4.1.1 on 2022-09-10 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildVersion',
            fields=[
                ('version_number', models.TextField(help_text='The version number of the build. Must be unique.', max_length=50, primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username', models.TextField(help_text='The username of the author of the PR', max_length=50, verbose_name="Author's Username")),
                ('author_url', models.URLField(help_text="The URL of the author's GitHub profile", max_length=512, verbose_name="Author's URL")),
                ('description', models.TextField(help_text='A short description of the change', max_length=512, verbose_name='Description')),
                ('pr_url', models.URLField(help_text='The URL of the PR that this change is associated with', max_length=512, verbose_name='PR URL')),
                ('pr_number', models.IntegerField(help_text='The number of the PR that this change is associated with', verbose_name='PR Number')),
                ('category', models.CharField(choices=[('NEW', 'New'), ('IMPROVEMENT', 'Improvement'), ('BALANCE', 'Balance'), ('FIX', 'Fix')], help_text='The category of the change', max_length=11, verbose_name='Category')),
                ('date_added', models.DateField(blank=True, help_text='The date that this change was added to the game', null=True, verbose_name='Date Added')),
                ('build', models.ForeignKey(default=None, help_text='The build that this change is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='app.buildversion', verbose_name='Build')),
            ],
        ),
    ]
