# Generated by Django 4.1.1 on 2022-09-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildversion',
            options={'ordering': ['-version_number']},
        ),
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['date_added']},
        ),
    ]
