# Generated by Django 4.1.5 on 2023-01-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_type_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='short_description',
        ),
    ]
