# Generated by Django 4.1.5 on 2023-01-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_state_alter_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('no-type', 'No category'), ('weekly', 'Weekly update'), ('announcement', 'Announcement')], default='no-type', max_length=12),
        ),
    ]
