# Generated by Django 4.1.5 on 2023-01-30 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_rename_body_post_deprecated_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Select the author of this post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time this post was created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='deprecated_body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Enter the body of this post (deprecated, use sections instead)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Unique value for post URL, created from title.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Enter a title for this post. This will displayed as an H1.', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('no-type', 'No category'), ('weekly', 'Weekly update'), ('announcement', 'Announcement'), ('community', 'Community Highlight')], default='no-type', help_text='Select the type of this post', max_length=12),
        ),
        migrations.AlterField(
            model_name='section',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Enter the body of this section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='heading',
            field=models.CharField(help_text='Enter a heading for this section. This will displayed as an H2.', max_length=200),
        ),
    ]
