# Generated by Django 4.1.5 on 2023-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_author_alter_post_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='heading',
            field=models.CharField(blank=True, help_text='Enter a heading for this section. This will displayed as an H2.', max_length=200, null=True),
        ),
    ]
