# Generated by Django 4.1.5 on 2023-02-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_section_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deprecated_body',
        ),
        migrations.AddField(
            model_name='post',
            name='socials_image',
            field=models.URLField(blank=True, help_text='Enter the URL of the image to be used for social media sharing. Default one will be chosen if empty.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Announcements, news and community highlights! Go read this blog post now!', help_text='Enter a summary of this post. This will be used for social media sharing.'),
            preserve_default=False,
        ),
    ]
